name: CI

on:
  push:
  pull_request:

jobs:
  testsuite:
    name: PHPUnit (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, apcu
          ini-values: apc.enable_cli = 1
          #coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Get date part for cache key
        id: key-date
        run: echo "date=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.php-version }}

      - name: Composer install
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit -c phpunit.xml.dist --colors=always

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, apcu
          tools: cs2pr
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Get date part for cache key
        id: key-date
        run: echo "date=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-8.4

      - name: Composer install
        run: composer install --prefer-dist --no-progress

      - name: Run PHP CodeSniffer
        run: composer cs-check

      - name: Run phpstan
        run: composer stan